# Generated by Django 2.0.1 on 2018-01-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRenderingStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ReportReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='flashParent',
        ),
        migrations.AddField(
            model_name='report',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportreport',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='client.Report'),
        ),
        migrations.AddField(
            model_name='reportreport',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='client.Report'),
        ),
        migrations.AddField(
            model_name='reportreport',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.ReportRelationshipType'),
        ),
        migrations.AddField(
            model_name='report',
            name='rendering_strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='client.ReportRenderingStrategy'),
        ),
    ]
