# Generated by Django 2.0.1 on 2018-01-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20180122_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='reportcompany',
            options={'verbose_name_plural': 'Report Companies'},
        ),
        migrations.RemoveField(
            model_name='reportcompany',
            name='private',
        ),
        migrations.AddField(
            model_name='company',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
