# Generated by Django 2.0.1 on 2018-01-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20180124_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportFileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='reportfile',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.ReportFileType'),
        ),
        migrations.AddField(
            model_name='report',
            name='tags',
            field=models.ManyToManyField(to='client.Tag'),
        ),
    ]
