# Generated by Django 2.0.1 on 2018-01-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20180124_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='primaryFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='report',
            name='sourceFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
