# Generated by Django 2.0.1 on 2018-01-25 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20180124_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfile',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reportfile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='reportreport',
            name='child',
        ),
        migrations.RemoveField(
            model_name='reportreport',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='reportreport',
            name='relationship',
        ),
        migrations.AddField(
            model_name='report',
            name='flashParent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flash_children', to='client.Report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='client.Tag'),
        ),
        migrations.AlterField(
            model_name='reportcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_mention', to='client.Company'),
        ),
        migrations.DeleteModel(
            name='ReportFile',
        ),
        migrations.DeleteModel(
            name='ReportFileType',
        ),
        migrations.DeleteModel(
            name='ReportReport',
        ),
    ]
